Repository owncloud/docs-client-ios-app, pull requests merged in 2021-09, with the labels that each got.

#4 Fixes to image sizes mainly in pdf, especially in tables
  modules/ROOT/pages/accounts.adoc
  modules/ROOT/pages/appendices/troubleshooting.adoc
  modules/ROOT/pages/available_offline.adoc
  modules/ROOT/pages/collaboration.adoc
  modules/ROOT/pages/files.adoc
  modules/ROOT/pages/files_integration.adoc
  modules/ROOT/pages/quick_access.adoc
  modules/ROOT/pages/security.adoc
  modules/ROOT/pages/settings.adoc
Labels: documentation

#3 Update of the manual_config file for makepdf to be inline with the other repos
  bin/manual_config
Labels: deployment

#5 [11.7] [PR 4] Fixes to image sizes mainly in pdf, especially in tables
  modules/ROOT/pages/accounts.adoc
  modules/ROOT/pages/appendices/troubleshooting.adoc
  modules/ROOT/pages/available_offline.adoc
  modules/ROOT/pages/collaboration.adoc
  modules/ROOT/pages/files.adoc
  modules/ROOT/pages/files_integration.adoc
  modules/ROOT/pages/quick_access.adoc
  modules/ROOT/pages/security.adoc
  modules/ROOT/pages/settings.adoc
Labels: backport

#6 [11.7] [PR 3] Update of the manual_config file for makepdf to be inline with the other repos
  bin/manual_config
Labels: backport

#8 Changes necessary for the new iOS App 11.7.1
  .drone.star
  site.yml
Labels: deployment

#9 Relocate images
  modules/ROOT/assets/images/appendices/troubleshooting/ios-app-settings-logging.png
  modules/ROOT/assets/images/appendices/troubleshooting/mitmproxy_screenshot.png
  modules/ROOT/assets/images/appendices/troubleshooting/owncloud-log-configuration.png
  modules/ROOT/assets/images/available-offline/all-available-offline-items.png
  modules/ROOT/assets/images/available-offline/available-offline-items.png
  modules/ROOT/assets/images/available-offline/available-offline-logo.png
  modules/ROOT/assets/images/available-offline/file-available-offline.png
  modules/ROOT/assets/images/available-offline/folder-action.png
  modules/ROOT/assets/images/available-offline/make-available-offline.png
  modules/ROOT/assets/images/available-offline/make-unavailable-offline.png
  modules/ROOT/assets/images/available-offline/offline-storage-settings.png
  modules/ROOT/assets/images/available-offline/one-folder-available-offline.png
  modules/ROOT/assets/images/available-offline/settings.png
  modules/ROOT/assets/images/files/21_File_list_annotated.png
  modules/ROOT/assets/images/files/21_File_list_parent.png
  modules/ROOT/assets/images/files/24_Upload_Photo_multi.png
  modules/ROOT/assets/images/files/26_Files_multidragdrop.png
  modules/ROOT/assets/images/files/26_Files_multidragdrop_iPad.png
  modules/ROOT/assets/images/files/41_PDF.png
  modules/ROOT/assets/images/files/42_PDF_toc.png
  modules/ROOT/assets/images/files/43_PDF_thumbs.png
  modules/ROOT/assets/images/files/44_PDF_search.png
  modules/ROOT/assets/images/files/create-new-folder.png
  modules/ROOT/assets/images/files/directory-actions.png
  modules/ROOT/assets/images/files/file-actions-multiple-files-selected.png
  modules/ROOT/assets/images/files/file-actions.jpg
  modules/ROOT/assets/images/files/file-with-same-name-already-exists.png
  modules/ROOT/assets/images/files/icon-download.png
  modules/ROOT/assets/images/files/icon-not-available-locally.png
  modules/ROOT/assets/images/files/index-bar-with-callout.png
  modules/ROOT/assets/images/files/sort-files-landscape-mode.png
  modules/ROOT/assets/images/files/sort-files-portrait-mode.png
  modules/ROOT/assets/images/files/view-file-image.png
  modules/ROOT/assets/images/files/view-file-odt.png
  modules/ROOT/assets/images/files/view-file-pdf.png
  modules/ROOT/assets/images/files/view-file-text-file.png
  modules/ROOT/assets/images/files/view-file-video.png
  modules/ROOT/pages/appendices/troubleshooting.adoc
  modules/ROOT/pages/available_offline.adoc
  modules/ROOT/pages/files.adoc
Labels: documentation

#10 [11.7] [PR 9] Relocate images
  modules/ROOT/assets/images/appendices/troubleshooting/ios-app-settings-logging.png
  modules/ROOT/assets/images/appendices/troubleshooting/mitmproxy_screenshot.png
  modules/ROOT/assets/images/appendices/troubleshooting/owncloud-log-configuration.png
  modules/ROOT/assets/images/available-offline/all-available-offline-items.png
  modules/ROOT/assets/images/available-offline/available-offline-items.png
  modules/ROOT/assets/images/available-offline/available-offline-logo.png
  modules/ROOT/assets/images/available-offline/file-available-offline.png
  modules/ROOT/assets/images/available-offline/folder-action.png
  modules/ROOT/assets/images/available-offline/make-available-offline.png
  modules/ROOT/assets/images/available-offline/make-unavailable-offline.png
  modules/ROOT/assets/images/available-offline/offline-storage-settings.png
  modules/ROOT/assets/images/available-offline/one-folder-available-offline.png
  modules/ROOT/assets/images/available-offline/settings.png
  modules/ROOT/assets/images/files/21_File_list_annotated.png
  modules/ROOT/assets/images/files/21_File_list_parent.png
  modules/ROOT/assets/images/files/24_Upload_Photo_multi.png
  modules/ROOT/assets/images/files/26_Files_multidragdrop.png
  modules/ROOT/assets/images/files/26_Files_multidragdrop_iPad.png
  modules/ROOT/assets/images/files/41_PDF.png
  modules/ROOT/assets/images/files/42_PDF_toc.png
  modules/ROOT/assets/images/files/43_PDF_thumbs.png
  modules/ROOT/assets/images/files/44_PDF_search.png
  modules/ROOT/assets/images/files/create-new-folder.png
  modules/ROOT/assets/images/files/directory-actions.png
  modules/ROOT/assets/images/files/file-actions-multiple-files-selected.png
  modules/ROOT/assets/images/files/file-actions.jpg
  modules/ROOT/assets/images/files/file-with-same-name-already-exists.png
  modules/ROOT/assets/images/files/icon-download.png
  modules/ROOT/assets/images/files/icon-not-available-locally.png
  modules/ROOT/assets/images/files/index-bar-with-callout.png
  modules/ROOT/assets/images/files/sort-files-landscape-mode.png
  modules/ROOT/assets/images/files/sort-files-portrait-mode.png
  modules/ROOT/assets/images/files/view-file-image.png
  modules/ROOT/assets/images/files/view-file-odt.png
  modules/ROOT/assets/images/files/view-file-pdf.png
  modules/ROOT/assets/images/files/view-file-text-file.png
  modules/ROOT/assets/images/files/view-file-video.png
  modules/ROOT/pages/appendices/troubleshooting.adoc
  modules/ROOT/pages/available_offline.adoc
  modules/ROOT/pages/files.adoc
Labels: backport

#11 Fix various issues
  modules/ROOT/pages/accounts.adoc
  modules/ROOT/pages/appendices/mdm.adoc
  modules/ROOT/pages/appendices/troubleshooting.adoc
  modules/ROOT/pages/collaboration.adoc
  modules/ROOT/pages/faq.adoc
  modules/ROOT/pages/files.adoc
  modules/ROOT/pages/files_integration.adoc
  modules/ROOT/pages/quick_access.adoc
  modules/ROOT/pages/security.adoc
  modules/ROOT/pages/settings.adoc
Labels: documentation

#12 [11.7] [PR 11] Fix various issues
  modules/ROOT/pages/accounts.adoc
  modules/ROOT/pages/appendices/mdm.adoc
  modules/ROOT/pages/appendices/troubleshooting.adoc
  modules/ROOT/pages/collaboration.adoc
  modules/ROOT/pages/faq.adoc
  modules/ROOT/pages/files.adoc
  modules/ROOT/pages/files_integration.adoc
  modules/ROOT/pages/quick_access.adoc
  modules/ROOT/pages/security.adoc
  modules/ROOT/pages/settings.adoc
Labels: backport

#13 Using release notes
  modules/ROOT/nav.adoc
  modules/ROOT/pages/appendices/release_notes.adoc
Labels: documentation

#14 [11.7] [PR 13] Using release notes
  modules/ROOT/nav.adoc
  modules/ROOT/pages/appendices/release_notes.adoc
Labels: backport
