Repository owncloud/docs-client-ios-app, pull requests merged in 2022-03, with the labels that each got.

#77 Fix broken internal link
  modules/ROOT/pages/appendices/troubleshooting.adoc
Labels: documentation

#78 [11.8] [PR 77] Fix broken internal link
  modules/ROOT/pages/appendices/troubleshooting.adoc
Labels: backport

#79 [11.7] [PR 77] Fix broken internal link
  modules/ROOT/pages/appendices/troubleshooting.adoc
Labels: backport

#81 Changes necessary for the upcoming 11.9 release
  .drone.star
  site.yml
Labels: deployment
