Repository owncloud/docs-client-ios-app, pull requests merged in 2022-01, with the labels that each got.

#28 Fixes a bunch of helper scripts for improved usability
  bin/find-orphaned-adoc-files
  bin/find-orphaned-attachment-files
  bin/find-orphaned-base
  bin/find-orphaned-example-files
  bin/find-orphaned-image-files
  bin/instructions_makepdf.md
  bin/makepdf
  bin/manual_config_pdf
Labels: deployment

#30 [11.7] [PR 28] Fixes a bunch of helper scripts for improved usability
  bin/find-orphaned-adoc-files
  bin/find-orphaned-attachment-files
  bin/find-orphaned-base
  bin/find-orphaned-example-files
  bin/find-orphaned-image-files
  bin/instructions_makepdf.md
  bin/makepdf
  bin/manual_config_pdf
Labels: backport

#29 [11.8] [PR 28] Fixes a bunch of helper scripts for improved usability
  bin/find-orphaned-adoc-files
  bin/find-orphaned-attachment-files
  bin/find-orphaned-base
  bin/find-orphaned-example-files
  bin/find-orphaned-image-files
  bin/instructions_makepdf.md
  bin/makepdf
  bin/manual_config_pdf
Labels: backport

#31 Text fixes in the new version branch description
  docs/new-version-branch.md
Labels: documentation

#32 [11.8] [PR 31] Text fixes in the new version branch description
  docs/new-version-branch.md
Labels: backport

#33 [11.7] [PR 31] Text fixes in the new version branch description
  docs/new-version-branch.md
Labels: backport

#37 Fix for makepdf refs #34
  bin/makepdf
Labels: deployment

#38 [11.8] [PR 37] Fix for makepdf refs #34
  bin/makepdf
Labels: backport

#39 [11.7] [PR 37] Fix for makepdf refs #34
  bin/makepdf
Labels: backport

#40 Move the attachments directory
  modules/ROOT/attachments/.gitkeep
Labels: deployment

#42 [11.7] [PR 40] Move the attachments directory
  modules/ROOT/attachments/.gitkeep
Labels: backport

#43 Minor text fixes
  README.md
  docs/the-branching-workflow.md
Labels: deployment

#44 [11.8] [PR 43] Minor text fixes
  README.md
  docs/the-branching-workflow.md
Labels: backport

#45 [11.7] [PR 43] Minor text fixes
  README.md
  docs/the-branching-workflow.md
Labels: backport

#46 Missed one text fix
  docs/the-branching-workflow.md
Labels: deployment

#47 Add Antora Site Structure Description for Docs
  README.md
  package.json
  yarn.lock
Labels: deployment

#49 [11.8][PR 47] Add Antora Site Structure Description for Docs
  README.md
  package.json
  yarn.lock
Labels: backport

#48 [11.7] [PR 47] Add Antora Site Structure Description for Docs
  README.md
  package.json
  yarn.lock
Labels: backport

#50 site.yml attribute fix
  site.yml
Labels: deployment

#52 [11.7] [PR 50] site.yml attribute fix
  site.yml
Labels: backport

#53 Updates deployment files to be in sync with docs
  .drone.star
  .prettierrc
  generator/generate-site.js
  package.json
  yarn.lock
Labels: deployment

#54 [11.8] [PR 53] Updates deployment files to be in sync with docs
  .drone.star
  .prettierrc
  generator/generate-site.js
  package.json
  yarn.lock
Labels: backport

#55 [11.7] [PR 53] Updates deployment files to be in sync with docs
  .drone.star
  .prettierrc
  generator/generate-site.js
  package.json
  yarn.lock
Labels: backport

#57 [11.8] [PR 56] chore: replace s3 server in drone config by secret
  .drone.star
Labels: backport

#58 [11.7] [PR 56] chore: replace s3 server in drone config by secret
  .drone.star
Labels: backport

#59 update of the new version branch documentation
  docs/new-version-branch.md
Labels: deployment

#60 [11.8] [PR 59] update of the new version branch documentation
  docs/new-version-branch.md
Labels: backport

#61 [11.7] [PR 59] update of the new version branch documentation
  docs/new-version-branch.md
Labels: backport

#62 Update the mdm table file for 11.7 only (hardcoded)
  modules/ROOT/pages/appendices/mdm_tables.adoc
Labels: documentation

#63 Update the mdm table file for 11.8 only (hardcoded)
  modules/ROOT/pages/appendices/mdm_tables.adoc
Labels: documentation

#15 Improve crash log description
  modules/ROOT/pages/appendices/troubleshooting.adoc
Labels: documentation

#65 [11.7] [PR 15] Improve crash log description
  modules/ROOT/pages/appendices/troubleshooting.adoc
Labels: backport

#66 [11.8] [PR 15] Improve crash log description
  modules/ROOT/pages/appendices/troubleshooting.adoc
Labels: backport

#67 adding a build command for staging
  package.json
Labels: deployment

#68 [11.8] [PR 67] adding a build command for staging
  package.json
Labels: backport

#69 [11.7] [PR 67] adding a build command for staging
  package.json
Labels: backport
