Repository owncloud/docs-client-ios-app, pull requests merged in 2024-01, with the labels that each got.

#181 Antora 3.1 upgrade
  .drone.star
  antora.yml
  bin/instructions_makepdf.md
  bin/linter
  bin/makepdf
  bin/manual_config_pdf
  docs/new-version-branch.md
  ext-antora/generate-index.js
  ext-asciidoc/ext-antora/generate-index.js
  ext-asciidoc/remote-include-processor.js
  ext-asciidoc/tabs.js
  package.json
  site.yml
  yarn.lock
Labels: deployment, dependencies

#183 [12.0] [PR 181] Antora 3.1 upgrade
  .drone.star
  antora.yml
  bin/instructions_makepdf.md
  bin/linter
  bin/makepdf
  bin/manual_config_pdf
  docs/new-version-branch.md
  ext-antora/generate-index.js
  ext-asciidoc/ext-antora/generate-index.js
  ext-asciidoc/remote-include-processor.js
  ext-asciidoc/tabs.js
  package.json
  site.yml
  yarn.lock
Labels: backport

#184 [11.11] [PR 181] Antora 3.1 upgrade
  .drone.star
  antora.yml
  bin/instructions_makepdf.md
  bin/linter
  bin/makepdf
  bin/manual_config_pdf
  docs/new-version-branch.md
  ext-antora/generate-index.js
  ext-asciidoc/ext-antora/generate-index.js
  ext-asciidoc/remote-include-processor.js
  ext-asciidoc/tabs.js
  package.json
  site.yml
  yarn.lock
Labels: backport

#185 Just a small internal link fix
  docs/new-version-branch.md
Labels: documentation

#186 [11.11] [PR 185] Just a small internal link fix
  docs/new-version-branch.md
Labels: backport

#188 Changes necessary for the 12.1 branch
  .drone.star
Labels: deployment
